file_format: "1"
id: cradio
name: Cradio/Sweep
type: shield
url: https://github.com/davidphilipbarr/Sweep
requires: [pro_micro]
features:
    - keys
siblings:
    - cradio_host_left
    - cradio_perpheral_left
    - cradio_peripheral_right
    - cradio_dongle
